# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Gyermekvasut/Gyermekvasut.sln
    - name: Build
      run: dotnet build ./Gyermekvasut/Gyermekvasut.sln --no-restore
    - name: Test
      run: dotnet test ./Gyermekvasut/Gyermekvasut.sln --no-build --verbosity normal
    # Run code analysis for all projects/solutions, such that code analysis violations break the build.
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        build-breaking: true
